### PR TITLE
Async_call -- preview implementation of async_call/3, async_call/4, yield/1, nb_yield/1, nb_yield/2

### PR DESCRIPTION
**Pull request by linearregression**
Draft implementation of async_call/3, async_call/4, yield/1, nb_yield/1, nb_yield/2.
* added tests on local and remote node executions.
* new yield_timeout in app.src to set the default timeout for yield because:
- * the RPC implementation defaults to infinity which on careless use will hang
- * so instead use an explicit setting in config that defaults to infinity to mimic the PRC behavior but makes this timeout less hidden

NB:
- same caveat of anonymous function execution on remote node
- nb_yield/1 per rpc doc has implicit default timeout of 0. I don't quite know what the use of this API.  "flushing?". If so,this is such a bad name.

### CODE REVIEW

**Comment by linearregression** [comment]
Can u take a look the remaining PR? Want to fix those once my machine come back to life
thanks

**Comment by priestjim** [comment]
I'm a little short on time these days, let's finish with the 2 previous PRs and I'll take a look at these ones after.

**Comment by linearregression** [comment]
Can you sync develop branch with master?

**Comment by linearregression** [comment]
https://github.com/priestjim/gen_rpc/pull/43 is a cleaned up, squashed version

**Pull request closed without merging**
