### PR TITLE
1st draft implementation of pinfo/1 and pinfo2 (build on PR#20)

### PR DESCRIPTION
**Pull request by linearregression**
* 1st draft implementation of pinfo/1 & 2
* basically delegate to gen_rpc:call for erlang process_info (notice rpc uses block_callfor pinfo/2 but not implemented yet)
*  **tests**: 
- call a longer running process so that Pid is still alive when initiate gen_rpc:pinfo
- call a process tht immediate exit
- call a living process for process status 
Same on remote node.

### CODE REVIEW

**Comment by priestjim** [comment]
I'll implement block_call and let you know so you update the PR! Thanks!

**Comment by priestjim** [comment]
I've also merged #20 so you can rebase off of develop

**Comment by linearregression** [comment]
I had a trial implementation of block_call, which I was not too sure about my approach. I am still getting used to the state machine of the project.
Instead of just scrap it I finish it off and submit as PR 26 for review.
https://github.com/priestjim/gen_rpc/pull/26
If you have time, have a look. Feel free to junk it if need to.

**Comment by priestjim** [comment]
I checked the otp source and I can't find a good enough reason as to why pinfo/2 should block_call, so let's just leave it at simple call!

**Comment by priestjim** [comment]
Also, I think we need some kind of organization with the test_server from the other PR and the dummy module here. Too many auxiliary modules, maybe we should consolidate?

**Comment by linearregression** [comment]
The PRs are kinda independent of each other. To be honest, block_call looks like this is exactly the thing gen_rpc is trying to solve. 

Those tests have grown a lot and are now hard to dig through. 

That test_server, I was about to junk it. The original intention was to have those eval_everywhere to change the state of the test_sever then use rpc to query the sate of test_server and do the reset. But rpc query always arrives faster than the gen_rpc. Those lines from rpc are left out.

How do you want to reorg?

**Comment by linearregression** [comment]
pinfo and that async_call PR are relatively cleaner

**Comment by linearregression** [comment]
any idea of multicall?  ''''a multicall is an RPC which is sent concurrently from one client to multiple servers"

**Comment by priestjim** [comment]
So for the eval_everywhere, you can timeout-poll until you get a good value. timer:sleep works fairly ok in these situations with a sufficiently large timeout (i.e. 1") - this is tests we're talking about, not production code. If you're gonna ditch the server we need to re-evaluate any auxiliary modules we need for tests.

**Comment by linearregression** [comment]
I ditch the test server which is used in eval everywhere so far.
*  opt for ping-pong among test script, master and slaves.
* Try to avoid overly rely on timeout so tests will run more smoothly on different environment.

Commit (PR23)
https://github.com/linearregression/gen_rpc/commit/a739418c46934bdb37b935129fd3ca68c78748cd

**Comment by priestjim** [comment]
What about the dummy file? Can't it be integrated in the helper somehow?

**Comment by linearregression** [comment]
Forgot about dummy.erl
I need to remove it. Don't think it is used.

**Comment by linearregression** [comment]
dummy is now removed.

**Pull request merged**
